### ISSUE TITLE
Track down intermittant test failures due response frame mismatch

### ISSUE THREAD

**Issue by bytesized** [mozilla/Snappy-Symbolication-Server#54]
I have seen a number of tests fail locally indicating that the response frame had the incorrect value. This is potentially very serious. Returning no frame data would be better than returning incorrect frame data.

**Comment by bytesized** [comment]
Well I just found one instance of failure that was due to two names in the same symbol file with the same offset and different frame values. Here is the raw symbol file as retrieved from the symbol server: [rapl](https://github.com/mozilla/Snappy-Symbolication-Server/files/537473/rapl.txt)

Line 159:

> FUNC 1590 23b 0 Domain::Domain

Line 568:

> PUBLIC 1590 0 Domain::Domain(char const*, unsigned int, Domain::IsOptional)

@ddurst Do you know how to determine which of these is the value that should be returned? Inspecting the [original implementation](https://github.com/mozilla/Snappy-Symbolication-Server/blob/e38f3fdd7b49ab181a95bd76bbd3a5f4fea97276/symParser.py#L20) reveals that it used to overwrite any earlier value with a later one of the same offset, prioritizing the last entry found. Is that what we want to do here?

**Comment by ddurst** [comment]
You should use the second one.

This is a little weird, because the second one is PUBLIC, and should be used over the FUNC one -- they have more information than the function ones.

(We're guaranteed (I think?) that PUBLIC ones will be listed last. So really, we should prefer PUBLIC over FUNC if we have it, and order guarantees us that we can use the second one if both are found.)

**Comment by bytesized** [comment]
This should be fixed by PR #57.
